## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
codecov: true
os:
  - linux
#  - osx
julia:
  - 1.0
  - 1
before_script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="Polyhedra", rev="master"))'
notifications:
  email: false
git:
  depth: 99999999
branches:
  only:
    - master
    - /^release-.*$/
